### ISSUE TITLE
Easy to reach Python max recursion depth and fail due to RuntimeError

### ISSUE THREAD

**Issue by treblig** [Flibber/Flibber#1]
After running for less than 24 hours, the following happens while running on an EC2 instance:

```
  File "flibber.py", line 490, in decider
    likeUsers(MAX_COUNT, 0, tag, 0, 0)
  File "flibber.py", line 408, in likeUsers
    data = reqURL(urlFindLike, post)
  File "flibber.py", line 114, in reqURL
    signature = hmac.new(CLIENT_SECRET, IP, sha256).hexdigest()
  File "/usr/lib/python2.7/hmac.py", line 133, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 55, in __init__
    if blocksize < 16:
RuntimeError: maximum recursion depth exceeded in cmp
```

It appears that both of us have modified the script a bit so the line numbers are off, but the bug still likely exists.

**Comment by ChipWolf** [comment]
Could you possibly provide more of the log? I've too had this issue, only with recursive errors however..

**Comment by ChipWolf** [comment]
Also, could you share your changes in a fork, I'd be interested to see them

**Comment by jubi468** [comment]
Heys, thanks for your reply! Actually I did not change anything, just changed the credentials for the Instagram...I was trying ti run it from IDLE and was getting this error..now tried to run through terminal and it seems to work! =)

**Comment by treblig** [comment]
Sure thing! I'm re-running it now since I lost the stack trace and will put it in here when I've got it. On the changes you made that I referenced, I pulled before this commit: https://github.com/Flibber/Flibber/commit/8e384d97197ee4e2b17c78fa2b74bfe5e9051e5b.

The only change I made was adding this block of code at line 288 (mine). The `400` is arbitrary. I added it because I had a case where subtracting 3600 caused it to be negative, thus crashing on `execPause()` :)

```
if len(likeArray) >= 100:
                waitTime = currentTime() - likeArray[0] - 3600
                if (waitTime > 0):
                    execPause(waitTime)
                else:
                    execPause(400)
```

**Comment by ChipWolf** [comment]
hence `if(waitTime > 0)`

**Comment by ChipWolf** [comment]
Make sure you grab the latest version @treblig

**Comment by treblig** [comment]
I pulled your most recent version, and it's fixed now!
