### ISSUE TITLE
'x-ratelimit-remaining' thrown with newest changes

### ISSUE THREAD

**Issue by treblig** [Flibber/Flibber#11]
```
[NUM#] Request #12
[RURL] https://api.instagram.com/v1/users/self/follows
[FLDS] 
[REDACTED]
[HTTP] GET
[ERRO] 'x-ratelimit-remaining'
[RTRY] Retrying request...
[NUM#] Request #13
[RURL] https://api.instagram.com/v1/users/self/follows
[FLDS]
[REDACTED]
[HTTP] GET
[ERRO] 'x-ratelimit-remaining'
[RTRY] Retrying request...
[NUM#] Request #14
[RURL] https://api.instagram.com/v1/users/self/follows
[FLDS] 
[REDACTED]
[HTTP] GET
[ERRO] 'x-ratelimit-remaining'
[RTRY] Retrying request...
^CTraceback (most recent call last):
  File "flibber.py", line 89, in headerFunction
    def headerFunction(header_line):
KeyboardInterrupt
[RURL] https://api.instagram.com/v1/users/self/follows
[FLDS]
[REDACTED]
[HTTP] GET

[INPT] Keyboard Interrupt!

[STAT] Statistics from run:
[STAT] Total Unfollows: 0
[STAT] Total Follows: 0
[STAT] Total Likes: 0
[STAT] Total API Calls: 15
```

**Comment by ChipWolf** [comment]
Cannot replicate. That would mean the Exception as e = 'x-ratelimit-remaining' on line 163 - 166

**Comment by ChipWolf** [comment]
Which means those keys are not in the response from Instagram. Which means it's not hitting the API properly, which means your options are incorrect?

**Comment by treblig** [comment]
Hmmm... I'm seeing it happen on both of my instances on 2 different EC2 boxes with 2 different accounts (different applications as well).

I tried getting a new `access_token` and a new `code`, and I'm still seeing it repro. In fact, the lines in `options.py` are identical to a version of the `flibber.py` that I have from before the separation into 2 files, except `LIKE_FOLLOW` is in quotes in the new version. My old version of `flibber.py` in a different directory from before the refactor still works as well.

**Comment by ChipWolf** [comment]
Hm, still can't repro. I've made quite a few changes today, mainly PEP8 fixes, if you clone the entire repo and modify the `options.py` manually, see if you have any luck then?

**Comment by ChipWolf** [comment]
I'm still trying to figure out why the hell 'x-ratelimit-remaining' is being cast into error_message

**Comment by ChipWolf** [comment]
Alright, managed to repro it.
Working on it

**Comment by ChipWolf** [comment]
Got a more detailed traceback:
![](https://i.starbs.net/08xm)

**Comment by ChipWolf** [comment]
Right. It appears Instagram are no longer using the ratelimit headers. Looking into why

**Comment by ChipWolf** [comment]
I spoke too soon, it seems it's due to missing parameters..
![](https://i.starbs.net/g7vQ)

**Comment by MichaelBanks** [comment]
Digging deeper

**Comment by ChipWolf** [comment]
Found the issue, line 115. My `options.` replace fucked up the post variables. Fixing.

**Comment by MichaelBanks** [comment]
Fixed.

**Comment by ChipWolf** [comment]
Fixed: https://github.com/Flibber/Flibber/commit/30f0fb1fb7c27f8231e4fc00302d0c2e36945656 https://github.com/Flibber/Flibber/commit/3b4cc136aea67b1de6ece03a377fc2eb6b70aec8

**Comment by treblig** [comment]
Nice fix! Working great for me now.

**Comment by ChipWolf** [comment]
Thanks for the support @treblig
