### ISSUE TITLE
keep getting OAuthPermissionsException

### ISSUE THREAD

**Issue by shaharbukra** [Flibber/Flibber#12]
Hi,,
after a while i manage to get Flibber to work...
it gets all the users  (getUsers() function ...)
it gets all the picture (getPics() function...)

but when it gets to the likeUsers im getting :
[RATE] Remaining API calls: 4684/5000
[RURL] https://api.instagram.com/v1/users/226576984/relationship
[FLDS] access_token=[token]&action=follow&client_id=[clientID]
[HTTP] POST
[CODE] 400
[TYPE] OAuthPermissionsException
[FAIL] This request requires scope=relationships, but this access token is not authorized with this scope. The user must re-authorize your application with scope=relationships to be granted write permissions.

So i read in the Instagram api and saw that my request at the beginning was for like and relation...
(on your option help, scope=likes+relationships...)

do you have any idea?
thanks,
Shahar.

**Comment by pontolab** [comment]
I belive Instagram changed their API slightly. See below for a different security tab of an API client created before and after April 2015.

before:
![beforeapi](https://cloud.githubusercontent.com/assets/6823810/7294926/6282574a-e9a9-11e4-987a-4186b94d3813.png)

after:
![afterapi](https://cloud.githubusercontent.com/assets/6823810/7294927/628442a8-e9a9-11e4-9a92-aeadfdc4d10f.png)

**Comment by shaharbukra** [comment]
Thanks, 
I will give it a try with this config...

**Comment by amiruqdah** [comment]
@pontolab @shaharbukra Disabling Implicit OAuth will actually break the script. Anyways, I just wanted to mention that the major revisions to the Instagram API have now made the "likes" and "relationships" endpoints restricted. You need to fill out a [form](https://help.instagram.com/contact/185819881608116#) for approval for special access.
