### ISSUE TITLE
Followers

### ISSUE THREAD

**Issue by Soverus** [Flibber/Flibber#17]
While watching the script, I've noticed that when a new person gets Followed, an action is taken on your current followers. For instance. 

92m200[0m
[[92mFLLW[0m] [92mFollowing count: 265<-[0m       #This here
[[92mRLAT[0m] [92mFollowing user 361759582[0m
[[95mNUM#[0m] [95m[1mRequest #572[0m
[[94mRATE[0m] [94mRemaining API calls: [91m4439/5000[0m[0m
[[94mRURL[0m] [94mhttps://api.instagram.com/v1/users/361759582/relationship[0m
[[94mFLDS[0m] [94maccess_token=1482256912.ab103e5.eb3bc3

When I started the script, I had 265 Following. It has followed about 220 so far, but what happens is that it looks at what your start amount is, and when it follows someone new- it doesn't increase that value +1, it instead copies your old value and pastes it back to that field. The only way that I'm showing that it writes over, is if after following these people- you go directly in to the app and manually follow someone. That sends user_input from your end and writes a new value to that field.

**Comment by ChipWolf** [comment]
Don't mess about with the app while using the bot?!
