### ISSUE TITLE
Modules not being found

### ISSUE THREAD

**Issue by jonhendershot** [Flibber/Flibber#18]
Having issues with the first run of the script starting on pycurl but seeming to run into similar issues with other module imports. I'm not too familiar with this, did I do something wrong? How can I remedy this? Would love to use this script!

![screen shot 2015-08-08 at 4 22 08 am](https://cloud.githubusercontent.com/assets/8424532/9149726/1a53e01c-3d85-11e5-899d-178931d02225.png)

**Comment by mrunknowntoman** [comment]
I did have the same issue so if anyone knows that would be great.

**Comment by mrunknowntoman** [comment]
![image](https://cloud.githubusercontent.com/assets/13898911/9402445/d414284a-4820-11e5-9a09-b09ef6b3b396.png)
I also had this issue where I couldn't even tell my return on the app
am I missing something?

@ChipWolf 

I ran the script below and tried to change both the code and access token to the access token from the uri return of the client ID and URL.
![image](https://cloud.githubusercontent.com/assets/13898911/9402500/881fa076-4821-11e5-9983-a819df891035.png)
Either way I run the command I still return nothing.

If anyone can help that would be great!
