### ISSUE TITLE
NameError: name 'messageHandler' is not defined

### ISSUE THREAD

**Issue by jubi468** [Flibber/Flibber#2]
When try to run, get this error

Traceback (most recent call last):
  File "/Users/Yaroslav/Downloads/Flibber-master/flibber.py", line 558, in <module>
    messageHandler(tCol.UNDERLINE + "Statistics from run:", "STAT", "WARNING")
NameError: name 'messageHandler' is not defined

**Comment by ChipWolf** [comment]
That's due to the script terminating before the messageHandler is registered, I'll look into possible causes

**Comment by ChipWolf** [comment]
Try the latest version
