### ISSUE TITLE
[ERRO] Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jubi468** [Flibber/Flibber#3]
After about 300 runs started getting this error:

[ERRO] Expecting value: line 1 column 1 (char 0)

And exited after this:

[EXEP] unsupported operand type(s) for +: 'int' and 'NoneType'

Statistics:

[STAT] Statistics from run:
[STAT] Total Unfollows: 0
[STAT] Total Follows: 46
[STAT] Total Likes: 120
[STAT] Total API Calls: 309

**Comment by ChipWolf** [comment]
@jubi468 Grab the latest version, you should get this issue.
