### ISSUE TITLE
Feature request: Break Creds / Params Into Their Own File

### ISSUE THREAD

**Issue by treblig** [Flibber/Flibber#6]
I'd like to be able to update the main logic with updates to the code without copying and pasting credentials and parameters each time. Could you break it into a separate file to do this? Is the best way for me to tell Git to ignore that file once I put the values in it?

**Comment by ChipWolf** [comment]
I'd accept a pull for that functionality, I've not had time to do that

**Comment by treblig** [comment]
Cool - I'll do that in the next few days and send you a pull request.

**Comment by ChipWolf** [comment]
Done.
