### ISSUE TITLE
NameError: name 'msg' is not defined error on execution

### ISSUE THREAD

**Issue by indie1982** [Flibber/Flibber#9]
I'm new to python so it might be something I'm doing wrong but when I run flibber.py after editing options.py I get the following error:

File "flibber.py", line 633, in <module>
    msg(tCol.UNDERLINE + "Statistics from run:", "STAT", "WARNING")
NameError: name 'msg' is not defined

Is it my fault? ;)

**Comment by gaetanoiachella** [comment]
idem same error

**Comment by 5p4ce** [comment]
Same here :/ any resolution for that?

**Comment by ChipWolf** [comment]
Your options are not filled in, so it's erroring before you even start

**Comment by ChipWolf** [comment]
Also, @eigentlichich @gaetanoiachella @indie1982, fixed in latest build
